# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-14 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
