# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-16 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privategroup',
            name='action_related',
        ),
        migrations.RemoveField(
            model_name='privategroup',
            name='user_created',
        ),
        migrations.AddField(
            model_name='privategroup',
            name='actionid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privategroup',
            name='userid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
