# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-18 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170116_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='notein',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fullname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'fullname'),
        ),
    ]
