# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-14 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170114_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default=b'users/avatars/noimage.png', max_length=255, upload_to=b'users/avatars'),
        ),
    ]
