# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-14 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170114_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendaraction',
            name='actionid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='calendaraction',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
