# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-14 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170114_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendaraction',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
