# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-18 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170118_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='actionid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='fromuser',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='touser',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
