# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-14 07:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20170114_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, null=True, verbose_name='Title')),
                ('firstPicture', models.ImageField(blank=True, upload_to=b'action/images')),
                ('content', models.TextField(max_length=30000, null=True, verbose_name=b'Details')),
                ('createDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name=b'CreatedDate')),
                ('startDate', models.DateTimeField(blank=True, null=True, verbose_name=b'StartDate')),
                ('endDate', models.DateTimeField(blank=True, null=True, verbose_name=b'EndDate')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name=b'timeUpdated')),
                ('isverified', models.BooleanField(default=False, verbose_name=b'isverified')),
                ('isactive', models.BooleanField(default=True, verbose_name=b'isActive')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
            },
        ),
    ]
