# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-16 07:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_useraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionid', models.IntegerField()),
                ('userid', models.IntegerField()),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Friend',
                'verbose_name_plural': 'Friends',
            },
        ),
        migrations.AddField(
            model_name='privategroup',
            name='members',
            field=models.ManyToManyField(related_name='members', to='core.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'createdate'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='fromuser',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='touser',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[(b'I', b'Invalid'), (b'T', b'Bad_Title'), (b'C', b'Copyright')], max_length=1),
        ),
    ]
