# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-18 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170118_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='inviation',
            new_name='invitation',
        ),
    ]
