# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-18 19:57
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20170118_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=1024, null=True, verbose_name='Title')),
                ('firstPicture', models.ImageField(blank=True, default=b'users/avatars/noimage.png', upload_to=b'mapaction/images')),
                ('content', models.TextField(max_length=30000, null=True, verbose_name=b'Details')),
                ('createDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name=b'CreatedDate')),
                ('timefromuser', models.DateTimeField(blank=True, null=True, verbose_name=b'StartDate')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name=b'timeUpdated')),
                ('isverified', models.BooleanField(default=False, verbose_name=b'isverified')),
                ('isactive', models.BooleanField(default=True, verbose_name=b'isActive')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='longitude/latitude')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapauthor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MapAction',
                'verbose_name_plural': 'MapActions',
            },
            managers=[
                ('gis', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameModel(
            old_name='Friend',
            new_name='FriendRequest',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='author',
        ),
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'verbose_name': 'FriendRequest', 'verbose_name_plural': 'FriendRequests'},
        ),
        migrations.AddField(
            model_name='like',
            name='mapactionid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='actionmapid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='friend_create_map_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='friendrequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FriendRequest'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notificationtype',
            field=models.CharField(choices=[(b'L', b'Liked'), (b'C', b'Commented'), (b'F', b'FriendRequest'), (b'I', b'Invitation'), (b'M', b'FriendCreateMapAction'), (b'A', b'Accepted'), (b'D', b'Deadlined'), (b'F', b'ClosedAction'), (b'R', b'ReplyComment')], max_length=1),
        ),
        migrations.DeleteModel(
            name='UserAction',
        ),
    ]
